services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://<username>:<password>@<cluster>.mongodb.net/contentvalor?retryWrites=true&w=majority
      - JWT_SECRET=${JWT_SECRET}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}